// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    schools,
    schoolYears,
    schoolContexts,
    teachingGroups,
    groupGrades,
    students,
    enrollments,
    attendanceDays,
    attendanceEntries,
    projects,
    projectGrades,
    projectFormativeFields,
    projectArticulatingAxes,
    activities,
    activityGrades,
    activityFormativeFields,
    activityRoster,
    activityEvaluations,
    studentRecords,
    studentRecordEntries,
  ];
  late final Shape0 schools = Shape0(
    source: i0.VersionedTable(
      entityName: 'schools',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 schoolYears = Shape1(
    source: i0.VersionedTable(
      entityName: 'school_years',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(ends_on >= starts_on)'],
      columns: [_column_0, _column_7, _column_8, _column_9],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 schoolContexts = Shape2(
    source: i0.VersionedTable(
      entityName: 'school_contexts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(school_id)'],
      columns: [_column_10, _column_11],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 teachingGroups = Shape3(
    source: i0.VersionedTable(
      entityName: 'teaching_groups',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK((schedule_start_minutes IS NULL AND schedule_end_minutes IS NULL)OR(schedule_start_minutes IS NOT NULL AND schedule_end_minutes IS NOT NULL AND schedule_start_minutes >= 0 AND schedule_start_minutes < 1440 AND schedule_end_minutes > schedule_start_minutes AND schedule_end_minutes < 1440))',
      ],
      columns: [
        _column_0,
        _column_12,
        _column_11,
        _column_1,
        _column_13,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 groupGrades = Shape4(
    source: i0.VersionedTable(
      entityName: 'group_grades',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(group_id, grade)'],
      columns: [_column_16, _column_17],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 students = Shape5(
    source: i0.VersionedTable(
      entityName: 'students',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_18, _column_19, _column_20, _column_21],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 enrollments = Shape6(
    source: i0.VersionedTable(
      entityName: 'enrollments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'FOREIGN KEY(group_id, grade)REFERENCES group_grades(group_id, grade)',
        'CHECK(list_number > 0)',
        'CHECK(ends_on IS NULL OR ends_on >= starts_on)',
      ],
      columns: [
        _column_0,
        _column_22,
        _column_23,
        _column_17,
        _column_24,
        _column_8,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 attendanceDays = Shape7(
    source: i0.VersionedTable(
      entityName: 'attendance_days',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(group_id, date)'],
      columns: [_column_0, _column_23, _column_26],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 attendanceEntries = Shape8(
    source: i0.VersionedTable(
      entityName: 'attendance_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(attendance_day_id, student_id)'],
      columns: [_column_27, _column_22, _column_28],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 projects = Shape9(
    source: i0.VersionedTable(
      entityName: 'projects',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_23,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 projectGrades = Shape10(
    source: i0.VersionedTable(
      entityName: 'project_grades',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id, grade)'],
      columns: [_column_33, _column_17],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 projectFormativeFields = Shape11(
    source: i0.VersionedTable(
      entityName: 'project_formative_fields',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id, formative_field)'],
      columns: [_column_33, _column_32],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 projectArticulatingAxes = Shape12(
    source: i0.VersionedTable(
      entityName: 'project_articulating_axes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id, articulating_axis)'],
      columns: [_column_33, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 activities = Shape13(
    source: i0.VersionedTable(
      entityName: 'activities',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_35, _column_29],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 activityGrades = Shape14(
    source: i0.VersionedTable(
      entityName: 'activity_grades',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(activity_id, grade)'],
      columns: [_column_36, _column_17],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 activityFormativeFields = Shape15(
    source: i0.VersionedTable(
      entityName: 'activity_formative_fields',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(activity_id)'],
      columns: [_column_36, _column_32],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape16 activityRoster = Shape16(
    source: i0.VersionedTable(
      entityName: 'activity_roster',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(activity_id, student_id)',
        'FOREIGN KEY(activity_id, grade)REFERENCES activity_grades(activity_id, grade)',
      ],
      columns: [_column_37, _column_22, _column_17],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 activityEvaluations = Shape17(
    source: i0.VersionedTable(
      entityName: 'activity_evaluations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(activity_id, student_id)',
        'FOREIGN KEY(activity_id, student_id)REFERENCES activity_roster(activity_id, student_id)',
        'CHECK(delivery_status = \'delivered\' OR achievement IS NULL)',
      ],
      columns: [_column_37, _column_22, _column_38, _column_39, _column_40],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 studentRecords = Shape18(
    source: i0.VersionedTable(
      entityName: 'student_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(student_id)'],
      columns: [_column_22, _column_41, _column_42, _column_43],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape19 studentRecordEntries = Shape19(
    source: i0.VersionedTable(
      entityName: 'student_record_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_22, _column_44, _column_45, _column_46],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cct =>
      columnsByName['cct']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get organization =>
      columnsByName['organization']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get state =>
      columnsByName['state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get municipality =>
      columnsByName['municipality']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get locality =>
      columnsByName['locality']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cct',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL UNIQUE',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'organization',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'state',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'municipality',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'locality',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get label =>
      columnsByName['label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startsOn =>
      columnsByName['starts_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endsOn =>
      columnsByName['ends_on']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'label',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'starts_on',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ends_on',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get schoolId =>
      columnsByName['school_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get schoolYearId =>
      columnsByName['school_year_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'school_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES schools(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'school_year_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES school_years(id)ON DELETE RESTRICT',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get schoolId =>
      columnsByName['school_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get schoolYearId =>
      columnsByName['school_year_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get shift =>
      columnsByName['shift']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get scheduleStartMinutes =>
      columnsByName['schedule_start_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get scheduleEndMinutes =>
      columnsByName['schedule_end_minutes']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'school_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES schools(id)ON DELETE RESTRICT',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'shift',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'schedule_start_minutes',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'schedule_end_minutes',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get grade =>
      columnsByName['grade']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'group_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES teaching_groups(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'grade',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get givenNames =>
      columnsByName['given_names']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get firstSurname =>
      columnsByName['first_surname']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get secondSurname =>
      columnsByName['second_surname']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get birthDate =>
      columnsByName['birth_date']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'given_names',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'first_surname',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'second_surname',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'birth_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get studentId =>
      columnsByName['student_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get grade =>
      columnsByName['grade']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get listNumber =>
      columnsByName['list_number']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get startsOn =>
      columnsByName['starts_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endsOn =>
      columnsByName['ends_on']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'student_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES students(id)ON DELETE RESTRICT',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'group_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES teaching_groups(id)ON DELETE RESTRICT',
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'list_number',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ends_on',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get date =>
      columnsByName['date']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'date',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get attendanceDayId =>
      columnsByName['attendance_day_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get studentId =>
      columnsByName['student_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'attendance_day_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES attendance_days(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lifecycle =>
      columnsByName['lifecycle']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get methodology =>
      columnsByName['methodology']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get formativeField =>
      columnsByName['formative_field']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'lifecycle',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'methodology',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'formative_field',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get grade =>
      columnsByName['grade']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'project_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES projects(id)ON DELETE CASCADE',
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get formativeField =>
      columnsByName['formative_field']! as i1.GeneratedColumn<String>;
}

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get articulatingAxis =>
      columnsByName['articulating_axis']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'articulating_axis',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'project_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES projects(id)ON DELETE RESTRICT',
    );

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get activityId =>
      columnsByName['activity_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get grade =>
      columnsByName['grade']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'activity_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES activities(id)ON DELETE CASCADE',
    );

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get activityId =>
      columnsByName['activity_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get formativeField =>
      columnsByName['formative_field']! as i1.GeneratedColumn<String>;
}

class Shape16 extends i0.VersionedTable {
  Shape16({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get activityId =>
      columnsByName['activity_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get studentId =>
      columnsByName['student_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get grade =>
      columnsByName['grade']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'activity_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES activities(id)ON DELETE RESTRICT',
    );

class Shape17 extends i0.VersionedTable {
  Shape17({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get activityId =>
      columnsByName['activity_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get studentId =>
      columnsByName['student_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deliveryStatus =>
      columnsByName['delivery_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get achievement =>
      columnsByName['achievement']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get observation =>
      columnsByName['observation']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'delivery_status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'achievement',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'observation',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape18 extends i0.VersionedTable {
  Shape18({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get studentId =>
      columnsByName['student_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get strengths =>
      columnsByName['strengths']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get difficulties =>
      columnsByName['difficulties']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get supports =>
      columnsByName['supports']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'strengths',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'difficulties',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'supports',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape19 extends i0.VersionedTable {
  Shape19({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get studentId =>
      columnsByName['student_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get occurredAt =>
      columnsByName['occurred_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get text =>
      columnsByName['text']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'occurred_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'text',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
