#!/usr/bin/env python3
"""Generate AulaRaíz's offline Mexico state/municipality catalog from INEGI.

Source: Servicio Web del Catálogo Único de Claves Geoestadísticas.
This script is for maintainers; the Flutter app never depends on the network.
"""

from __future__ import annotations

import json
import time
import urllib.request
from pathlib import Path

BASE_URL = "https://gaia.inegi.org.mx/wscatgeo/v2"
OUTPUT = Path("lib/core/catalogs/mexico_geography_catalog.dart")


def fetch_json(url: str) -> dict:
    request = urllib.request.Request(
        url,
        headers={"User-Agent": "AulaRaiz-catalog-generator/1.0"},
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.loads(response.read().decode("utf-8"))


def dart_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    states = fetch_json(f"{BASE_URL}/mgee/").get("datos", [])
    if len(states) != 32:
        raise RuntimeError(f"Expected 32 states from INEGI, received {len(states)}")

    entries: list[tuple[str, str, list[str]]] = []
    for index, state in enumerate(states):
        code = state["cve_ent"]
        name = state["nomgeo"]
        municipalities = fetch_json(f"{BASE_URL}/mgem/{code}").get("datos", [])
        names = sorted(item["nomgeo"] for item in municipalities)
        if not names:
            raise RuntimeError(f"INEGI returned no municipalities for {code} {name}")
        entries.append((code, name, names))
        if index + 1 < len(states):
            time.sleep(0.2)

    lines = [
        "// Generated by tool/generate_mexico_catalog.py from INEGI's",
        "// Catálogo Único de Claves Geoestadísticas. Do not edit manually.",
        "final class MexicoStateOption {",
        "  const MexicoStateOption({",
        "    required this.code,",
        "    required this.name,",
        "    required this.municipalities,",
        "  });",
        "",
        "  final String code;",
        "  final String name;",
        "  final List<String> municipalities;",
        "}",
        "",
        "abstract final class MexicoGeographyCatalog {",
        "  static const List<MexicoStateOption> states = <MexicoStateOption>[",
    ]

    for code, name, municipalities in entries:
        lines.extend(
            [
                "    MexicoStateOption(",
                f"      code: {dart_string(code)},",
                f"      name: {dart_string(name)},",
                "      municipalities: <String>[",
            ]
        )
        lines.extend(f"        {dart_string(item)}," for item in municipalities)
        lines.extend(["      ],", "    ),"])

    lines.extend(
        [
            "  ];",
            "",
            "  static MexicoStateOption? byCode(String code) {",
            "    for (final state in states) {",
            "      if (state.code == code) return state;",
            "    }",
            "    return null;",
            "  }",
            "}",
            "",
        ]
    )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {OUTPUT} with {len(entries)} states")


if __name__ == "__main__":
    main()
